version: "3.9"

services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=construction
      - POSTGRES_USER=construction
      - POSTGRES_PASSWORD=construction
    ports:
      - "5432:5432"
