# Generated by Django 4.0.6 on 2022-07-10 00:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='name')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='name')),
                ('website', models.URLField(max_length=400, verbose_name='website')),
                ('domain_name', models.CharField(db_index=True, help_text='Example: `example.com`', max_length=100, verbose_name='domain name')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price amount', max_digits=22, verbose_name='amount')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.offer', verbose_name='offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='products.product', verbose_name='products'),
        ),
        migrations.AddField(
            model_name='offer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.supplier', verbose_name='supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('product', 'supplier')},
        ),
    ]
